//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMSapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorProduct
    {
        public int VendorProductId { get; set; }
        public int ProductId { get; set; }
        public int Rate { get; set; }
        public int VendorBranchId { get; set; }
        public int VendorId { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual VendorBranch VendorBranch { get; set; }
    }
}
